version: '2'
services:
    node1: 
        image: cynical-chain:1
        environment:
            - JAVA_OPTS=-Dblockchain.nodeName=node1 -Dakka.remote.netty.tcp.hostname=node1
        ports:
            - "9000:9000"
            
    node2:
        image: cynical-chain:1
        links: 
            - node1:node1
        environment:
            - JAVA_OPTS=-Dblockchain.nodeName=node2 -Dblockchain.seedHost=akka.tcp://BlockChain@node1:2552/user/peerToPeerActor
        ports:
            - "9001:9000"
    node3:
        image: cynical-chain:1
        links: 
            - node1:node1
        environment:
            - JAVA_OPTS=-Dblockchain.nodeName=node3 -Dblockchain.seedHost=akka.tcp://BlockChain@node1:2552/user/peerToPeerActor
        ports:
            - "9002:9000"
    node4:
        image: cynical-chain:1
        links: 
            - node1:node1
        environment:
            - JAVA_OPTS=-Dblockchain.nodeName=node4 -Dblockchain.seedHost=akka.tcp://BlockChain@node1:2552/user/peerToPeerActor
        ports:
            - "9003:9000"

